title                 : AJL Blog
email                 : 
description: >- 
  Writing docs and stuff.
baseurl               : ""
url                   : http://annjulyleon.github.io
github_username       : annjulyleon

#theme                 : minimal-mistakes-jekyll
remote_theme          : mmistakes/minimal-mistakes
minimal_mistakes_skin : default
search                : true
words_per_minute      : 150

markdown              : kramdown
highlighter           : rouge
permalink             : /:categories/:title/
paginate              : 5
paginate_path         : /page:num/
timezone              : Europe/Moscow
locale                : "ru-RU"

teaser                : /assets/images/default/teaserfallback.png
logo                  : /assets/images/default/logo.png

include:
  - _pages
  
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name                : "Anna Leonova"
  avatar              : "/assets/images/default/bio-photo.jpg"
  bio                 : "That's me!"
  location            : "Moscow, Russia"
  links:
    - label           : "GitHub"
      icon            : "fab fa-fw fa-github"
      url             : "https://github.com/annjulyleon"
    - label           : "LinkedIn"
      icon            : "fab fa-fw fa-linkedin"
      url             : "https://www.linkedin.com/in/annleonova/"

footer:
  links:
    - label           : "GH"
      icon            : "fab fa-fw fa-github"
      url             : "https://github.com/annjulyleon"
    - label           : "LI"
      icon            : "fab fa-fw fa-linkedin"
      url             : "https://www.linkedin.com/in/annleonova/"

encoding              : "utf-8"
 
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      show_date: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true